/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'PatO' at '6/18/15 1:07 AM' with Gradle 2.2.1
 *
 * @author PatO, @date 6/18/15 1:07 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
